# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b2080d89fd90b411ed84a7221a848e578420ad192c1c6ff0345f62686d52a2712836d267e9f69f446182086d698b1e530d7379b8b28df1a0d400d8d8d8a8441

test:
  secret_key_base: 8c42b360a1060039e13d5595bc3bc224e8b992302c3f9abdad57d784dc9f06d4137ae0d35db1dfde6391ec7d272e2e9c84d37f4805dae25b581721477c5ccc5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
